stage("Tests"){
  node("xvfb"){
      wrap ([$class: 'Xvfb']){
        echo "Tests running"
        //Setup Node
        def nodeHome = tool 'Stable V6 Terra'
        env.PATH = "${nodeHome}/bin:${env.PATH}"
        //sh 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
        sh "if [ ! -f ${nodeHome}/bin/node ]; then ln -s ${nodeHome}/bin/nodejs ${nodeHome}/bin/node; fi"

        //git url: 'https://github.com/terra-arcana/terra-arcana', branch: 'development'
        checkout scm
        env.DISPLAY = ":0"
        sh 'npm install -g esdoc karma webpack'
        sh 'npm install'
        sh './node_modules/.bin/webpack'
        //sh 'esdoc'
        sh 'xvfb-run ./node_modules/.bin/karma start'
      }
  }
}

stage("Packaging"){
  node ("docker"){
      echo "Image packaging"
  }
}

stage("Deployment"){
  node {
      echo "Image deploying"
  }
}
