stage("Tests"){
  node("xvfb"){
      wrap ([$class: 'Xvfb', debug: true, displayName: 99, displayNameOffset: 0, installationName: 'Xvfb', screen: '1024x758x24']){
        echo "Tests running"
        //Setup Node
        def nodeHome = tool 'Stable V6 Terra'
        env.PATH = "${nodeHome}/bin:${env.PATH}"
        //sh 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
        sh "if [ ! -f ${nodeHome}/bin/node ]; then ln -s ${nodeHome}/bin/nodejs ${nodeHome}/bin/node; fi"

        //git url: 'https://github.com/terra-arcana/terra-arcana', branch: 'Jenkins_pipeline'
        checkout scm
        
        sh 'npm install -g esdoc karma webpack'
        sh 'npm install'
        sh './node_modules/.bin/webpack'
        //sh 'esdoc'
        withEnv(['DISPLAY=:99', 'CHROME_BIN=chromium']){
            sh './node_modules/.bin/karma start --browsers Chrome_without_sandbox'
        }
        junit 'build-reports/*.xml'

      }
  }
}

stage("Packaging"){
  node ("docker"){
      echo "Image packaging"
      checkout scm
      docker.withRegistry([credentialsId: 'dockerhub-chapeau']) {
        def newApp = docker.build "terraarcana/terra-arcana-dev:${env.BUILD_TAG}"
        newApp.push()
        newApp.push 'latest'
    }
  }
}

stage("Deployment"){
  node ("pure"){
      echo "Image deploying"
  }
}
